# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         SOAP-Lite-InstanceExporter
version:      0.02
version_from: InstanceExporter.pm
installdirs:  site
requires:
    SOAP::Lite:                    0.47

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
